version: "3.9"
services:
  timescaledb:
    container_name: timescaledb
    build: ./timescaledb
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./timescaledb/sql_files
        target: /timescaledb/sql_filles
      - type: bind
        source: ./timescaledb/nyc_data
        target: /seed
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2048M

  mock-devices:
    container_name: mockdevices
    build: ./mock_devices