version: "3.9"
services:
  seeded_timescaledb:
    container_name: seeded_timescaledb
    build: .
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2048M